/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.audiovisualizerview;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import android.app.Activity;
import com.pheelicks.utils.TunnelPlayerWorkaround;
import android.content.Context;

@Kroll.module(name = "Audiovisualizerview", id = "ti.audiovisualizerview")
public class AudiovisualizerviewModule extends KrollModule {
	@Kroll.constant
	public static final int AUDIOSESSION_OUTPUTMIX = 0;

	private static final String LCAT = "Pheelicks";

	@Override
	public void onResume(Activity activity) {
		Log.d(LCAT, "[MODULE LIFECYCLE EVENT] resume");
		Context context = TiApplication.getInstance().getApplicationContext();
		TunnelPlayerWorkaround.createSilentMediaPlayer(context);
		super.onResume(activity);
	}

	public AudiovisualizerviewModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(LCAT, "inside onAppCreate");
	}

}
