/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.audiovisualizerview;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;

import org.appcelerator.titanium.TiC;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiCompositeLayout.LayoutArrangement;
import org.appcelerator.titanium.view.TiUIView;
import org.appcelerator.titanium.TiApplication;

import com.pheelicks.utils.*;
import com.pheelicks.visualizer.*;
import com.pheelicks.visualizer.renderer.*;

import android.app.Activity;
import android.content.res.*;

@Kroll.proxy(creatableInModule = AudiovisualizerviewModule.class)
public class VisualizerViewProxy extends TiViewProxy {
	// Standard Debugging variables
	private static final String LCAT = "AVView";
	public int audioSessionId =0;
	public int renderType =0;

	TiApplication appContext;
	Activity activity;

	// Constructor
	public VisualizerViewProxy() {
		super();
		appContext = TiApplication.getInstance();
		activity = appContext.getCurrentActivity();
	}

	@Override
	public TiUIView createView(Activity activity) {
		TiUIView view = new VisualizerView(this);
		view.getLayoutParams().autoFillsHeight = true;
		view.getLayoutParams().autoFillsWidth = true;
		return view;
	}

	// Handle creation options
	@Override
	public void handleCreationDict(KrollDict options) {
		super.handleCreationDict(options);
		// https://github.com/m1ga/com.miga.gifview/blob/master/android/src/com/miga/tigifview/GifViewProxy.java#L106-L116

	}

	private class VisualizerView extends TiUIView {
		
		public VisualizerView(final TiViewProxy proxy) {
			super(proxy);
			String packageName = proxy.getActivity().getPackageName();
			Resources resources = proxy.getActivity().getResources();
			
			LayoutArrangement arrangement = LayoutArrangement.DEFAULT; // http://docs.appcelerator.com/module-apidoc/latest/android/index.html?org/appcelerator/titanium/view/TiCompositeLayout.LayoutArrangement.html
			/*
			 * In Titanium module we can convert native controls into Titanium
			 * view using setNativeView method. setNativeView sets the
			 * nativeView to view.
			 */
			setNativeView(new TiCompositeLayout(proxy.getActivity(),
					arrangement));
		}

		@Override
		public void processProperties(KrollDict props) {
            if (props.containsKey("audioSessionId")) {
            	audioSessionId = TiConvert.toInt(props, "audioSessionId");
            }
            if (props.containsKey("renderType")) {
            	renderType = TiConvert.toInt(props, "renderType");
            }
			super.processProperties(props);
			
		}
	}

}